# Generated by Django 5.2.17 on 2026-08-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ganancias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_productos_vendidos', models.PositiveIntegerField(default=0)),
                ('numero_ventas', models.PositiveIntegerField(default=0)),
                ('top_productos', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Análisis Mensual',
                'verbose_name_plural': 'Análisis Mensuales',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='AnalisisSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ganancias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_productos_vendidos', models.PositiveIntegerField(default=0)),
                ('numero_ventas', models.PositiveIntegerField(default=0)),
                ('top_productos', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Análisis Semanal',
                'verbose_name_plural': 'Análisis Semanales',
                'ordering': ['-anio', '-semana'],
                'unique_together': {('semana', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='ReporteStockBajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False)),
                ('producto_variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.productovariante')),
            ],
            options={
                'verbose_name': 'Reporte de Stock Bajo',
                'verbose_name_plural': 'Reportes de Stock Bajo',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
