# Generated by Django 5.2.17 on 2026-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisismensual',
            name='productos_menos_vendidos',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='analisismensual',
            name='promedio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='analisismensual',
            name='venta_mas_alta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='analisismensual',
            name='venta_mas_baja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='analisissemanal',
            name='productos_menos_vendidos',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='analisissemanal',
            name='promedio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='analisissemanal',
            name='venta_mas_alta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='analisissemanal',
            name='venta_mas_baja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
